---
- name: is ssh ready
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: check ssh state
      become: no
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local
    - name: set hostname
      hostname:
        name: '{{ inventory_hostname }}'
    - name: edit hosts
      lineinfile:
        path: /etc/hosts
        line: '{{ hostvars[item]["ansible_host"] }} {{ hostvars[item]["inventory_hostname"] }}'
      with_items: '{{ groups["servers"] }}'
      


- name: install s1
  hosts: s1
  become: yes
  roles:
    - ansible-clickhouse
    - lean_delivery.java
    - idealista.zookeeper_role
  pre_tasks:
    - name: create target folder
      file:
        path: /etc/clickhouse-server/
        state: directory
        mode: '0666'
    - name: create cluster template file
      template:
        src: files/cluster.xml.j2
        dest: /etc/clickhouse-server/cluster.xml
        mode: '0644'
  tasks:
    - name: start service
      service:
        name: clickhouse-server
        state: restarted

- name: install s2
  hosts: s2
  become: yes
  roles:
    - ansible-clickhouse
  pre_tasks:
    - name: create target folder
      file:
        path: /etc/clickhouse-server/
        state: directory
        mode: '0666'
    - name: create cluster template file
      template:
        src: files/cluster.xml.j2
        dest: /etc/clickhouse-server/cluster.xml
        mode: '0644'
  tasks:
    - name: start service
      service:
        name: clickhouse-server
        state: restarted

- name: deploy data
  hosts: s1
  tasks:
    - name: if table exists
      shell: clickhouse-client --database default --query "EXISTS TABLE ch_replicated_local"
      register: result
    - name: drop table
      shell: clickhouse-client --database default --query "DROP TABLE ch_replicated_local"
      when: result.stdout == '1'
    - name: if distributed table exists
      shell: clickhouse-client --database default --query "EXISTS TABLE ch_replicated_distributed"
      register: result
    - name: drop distributed table
      shell: clickhouse-client --database default --query "DROP TABLE ch_replicated_distributed"
      when: result.stdout == '1'
    - name: copy init table query file
      copy:
        src: files/replicated_table.sql
        dest: .
    - name: exec init table query
      shell: clickhouse-client --database default --queries-file replicated_table.sql
    - name: copy init distributed query file
      copy:
        src: files/distributed_table.sql
        dest: .
    - name: exec init distributed table query
      shell: clickhouse-client --database "default" --queries-file distributed_table.sql
    - name: copy dataset
      copy:
        src: files/dataset.csv
        dest: .
    - name: exec query
      shell: clickhouse-client --query "INSERT INTO ch_replicated_local FORMAT CSV" < dataset.csv
