---
driver:
  name: hetznercloud
lint: |
  set -e
  yamllint .
platforms:
  - name: ${MOLECULE_TEST_SCOPE:-default}-instance1
    server_type: cx11
    image: ${MOLECULE_PLATFORM-debian-10}
    groups:
      - clickhouse

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        test_database: scooby_doo
        clickhouse_kafka_client_users:
          - username: guest
            password: guest
        clickhouse_databases:
          - "{{ test_database }}"
      clickhouse:
        clickhouse_replica_id: single-replica
        clickhouse_interserver_http_host: "{{ ansible_default_ipv4.address }}"
        clickhouse_listen_addresses:
          - "{{ ansible_default_ipv4.address }}"
        clickhouse_timezone: Europe/Berlin
        clickhouse_display_name: default-instance1-ch
        clickhouse_replication_port: 9009
        clickhouse_zookeeper_credentials: bob:secret_password
        clickhouse_zookeeper_hosts: []
  lint: |
    set -e
    ansible-lint
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
    verify: verify/main.yml
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
