---
- name: Prepare the test environment by installing and configuring clickhouse, server and client.
  hosts: all
  vars:
    clickhouse_conf_dir: "/etc/clickhouse-server"
    clickhouse_logs_conf: "{{ clickhouse_conf_dir }}/config.d/log-level.xml"
    clickhouse_loglevel: "information"
  tasks:
    - include_role:
        name: ansible-role-clickhouse
