---
- name: install
  hosts: all
  become: yes
  roles:
    - ansible-clickhouse
    - lean_delivery.java
    - idealista.zookeeper_role
  tasks:
    - name: start service
      service:
        name: clickhouse-server
        state: restarted
