---
- name: install
  hosts: all
  become: yes
  roles:
    - ansible-clickhouse
  tasks:
    - name: start service
      service:
        name: clickhouse-server
        state: restarted
    - name: copy geoIP files
      copy:
        src: '{{ item }}'
        dest: /var/lib/clickhouse/user_files
        owner: clickhouse
        group: clickhouse
      with_items:
        - files/GeoLite2-Country-Blocks-IPv4.csv
        - files/GeoLite2-Country-Locations-en.csv
