---
- name: Verify ClickHouse state
  hosts: all
  tasks:
    - include_tasks: base.yml
      vars:
        clickhouse_conf_dir: "/etc/clickhouse-server"
        clickhouse_logs_conf: "{{ clickhouse_conf_dir }}/config.d/log-level.xml"
        clickhouse_loglevel: "information"
